num1 = int(input('Enter your number: '))
num2 = int(input('Enter your number: '))
num3 = int(input('Enter your number: '))
num4 = int(input('Enter your number: '))
num5 = int(input('Enter your number: '))

print(num1 + num2, num1 * num2, num1 // num2, num1 - num2)
print(num2 + num3, num2 * num3, num2 // num3, num2 - num3)
print(num3 + num4, num3 * num4, num3 // num4, num3 - num4)
print(num4 + num5, num4 * num5, num4 // num5, num4 - num5)
print(num5 + 25, num5 * 25, num5 // 25, num5 - 25)